[package]
name = "ow-wamr"
version = "0.1.0"
authors = ["PhilippGackstatter <philipp.gackstatter@student.tuwien.ac.at>"]
edition = "2018"

[dependencies]
wamr-sys = { version = "0.1" }
anyhow = "1.0"
serde_json = "1.0"
dashmap = "4.0.2"
ow-common = { path = "../ow-common" }
lazy_static = "1.4.0"