[package]
name = "ow-wamr-san"
version = "0.1.0"
authors = ["PhilippGackstatter <philipp.gackstatter@student.tuwien.ac.at>"]
edition = "2018"

[dependencies]
wamr-sys = { path = "../wamr-sys" }
anyhow = "1.0"
serde_json = "1.0"
dashmap = "4.0.2"
ow-common = { path = "../ow-common" }
lazy_static = "1.4.0"
